version: '3'
services:
  server:
    image: "vuesample/crud-server"
    ports:
     - "8090:8000"
    volumes:
     - ${_PWD}/django:/work
    user: "${_UID}:${_GID}"
    working_dir: /work
    command: python manage.py runserver 0.0.0.0:8000
  front:
    image: "vuesample/crud"
    environment:
     - HOME=/work
    ports:
     - "8080:8080"
    volumes:
     - ${_PWD}/vue/crud:/work
    user: "${_UID}:${_GID}"
    working_dir: /work
    command: sleep infinity
