version: '3'
services:
  server:
    image: "vuesample/crud-server"
    ports:
     - "8090:8000"
    volumes:
     - ${PWD}/django:/work
    user: "${UID}:${GID}"
    working_dir: /work
    command: python manage.py runserver 0.0.0.0:8000
  front:
    image: "vuesample/crud"
    ports:
     - "8080:8080"
    volumes:
     - ${PWD}/vue/crud:/work
    user: "${UID}:${GID}"
    working_dir: /work
    command: sleep infinity
